### ISSUE TITLE
Track jellyfin and DataHoarder backports

### ISSUE THREAD

**Issue by TheOneric** [libass/JavascriptSubtitlesOctopus#136]
This issue tracks what has and hasn't been backported from jellyfin and DataHoarder yet. Also some future improvements discussed in #111 but also not present in either of those have been included into the list. 
For reference: #111 has most of the jellyfin features from 2021.09 except for the smart/tiled blending, but also kept the confusing commit distribution and descriptions as well as bugs from the original implementation. It thus need(ed|s) to be split for better reviewability, future maintainability and to find and fix the bugs before they hit master.

The items can mostly be worked on in any order, not just the one they are listed in.

 - [x] Various bugfixes to what already existed in master *(should be mostly backoprted at this point, though it's possibly some are still lurking in the commits)
 - [x] Fixes/polyfills for old browser engines (*still found in eg Smart-TVs*; see #112 and #114)
 - [x] Unification of renderMode options into one `renderMode` setting (#118)
 - [x] Option to limit the canvas size (#119, #127)
 - [x] refactor internal buffers (#133)
 - [x] `dropAllAnimations` (#134)
 - [ ] The core jellyfin feature: `renderAhead`
   - though, the mode as originally implemented can get worse than `wasmBlend` once it fell behind schedule. A backoprt should ideally thus directly include a fix for that, one approach *(untested)* can be found e.g. here: https://github.com/jellyfin/JavascriptSubtitlesOctopus/pull/25
   - possible change from jellyfin: consider to consolidate all `renderAhead` options into a single structured object
   - related: once  this has been backoprted an example should also be added to the `gh_pages` branch. Possibly duplicate the Karaoke Stress Test sample for all three of `lossy`, `wasmBlend` and `wasmBlend+renderAhead` so there's a direct comparision.
  - [ ] “Smart/Tiled Blending” to avoid creating and sending large mostly empty frames on higher resolutions
  - [ ] DataHoarder
     - [ ] lazy font loading and other font improvements
     - [x] fix fontconfig cache dir
     - [x] reject renderingModes not support by the runtime
 - [ ] Future: check if `renderAhead` can be made to work with renderingmodes other than `wasmBlend`
 - [ ] Future: replace the continuous rescaling hacks with something proper
